spring.application.name=api
# Configurações de Conexão com o Banco 
spring.datasource.url=jdbc:postgresql://localhost:5432/pet_resgate_db
spring.datasource.username=postgres
spring.datasource.password=Allyn1809

# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true